blank_issues_enabled: false
contact_links:
  - name: Parallax Forums
    url: https://forums.parallax.com/discussion/178033/p2-usd-card-driver-fat32-filesystem-spin2-pasm2
    about: Ask questions and discuss this project on the Parallax Forums
  - name: P2 Documentation
    url: https://www.parallax.com/propeller-2/documentation/
    about: Official Propeller 2 documentation and resources
